[package]
org = "choreo"
name = "guardrail.pii_masking_guardrails_ai"
version = "1.0.0"
export = ["guardrail.pii_masking_guardrails_ai"]
distribution = "2201.5.5"
keywords = ["choreo-apim-mediation-policy","choreo-apim-mediation-request-flow","choreo-apim-mediation-response-flow","choreo-apim-egress-ai"]
visibility="private"

[build-options]
observabilityIncluded = true
